# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08b056b63937af210cc3c217df77873bb881a934fd14ce48acfa05b362dd8633874b65f4fe3cbe075f5e408b829189078687b76eb2764c2f696fc9c63bbf5597

test:
  secret_key_base: 5181d821c5d2a907f9a8ec80aea4ca0e56ef540551e19381139b6c196533f9f83220a130e3ee8ea14892dd9a8e0d8ad0e592a5d98a2add632c785327c24e20bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
